---
- name: Install ruby
  hosts: default
  become: true
  tasks:
    - name: Apt install ruby
      apt:
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
        state: present
        update_cache: yes
      register: result
      until: result is not failed
      retries: 5
      delay: 5
