---
- name: Install and enable mongo
  become: true
  tasks:
    - name: Apt install mongo
      apt:
        name:
          - mongodb
        state: present
        update_cache: yes

    - name: Enable mongodb
      systemd:
        name: mongodb
        state: started
        enabled: true
